<?php
include 'header.html';
?>
<link rel="stylesheet" href="investigadores.css">
<section id="articulos">
	<article>
			<h2>LA PARTICIPACION CIUDADANA EN LOS PRESUPUESTOS PARTICIPATIVOS Caso sur Peruano, ¿Es problema u oportunidad?</h2>
			<em>Jhenry William Sonco Justo <br>
	Sociólogo <br>
	Jerrysj19@hotmail.com
	</em>
			<h3>Introducción</h3>
			<p>
			El nuevo proceso de descentralización en el país trajo con sigo un nuevo marco normativo que incorpora la participación ciudadana en la toma de decisiones de la gestión local. Esta presencia se da a través de los procesos de planificación concertada del desarrollo (Planes estratégicos), la programación del presupuesto público (Presupuesto Participativo) y en la fiscalización y control social (Vigilancia ciudadana).
	Los antecedentes inmediatos del desarrollo de los procesos participativos a mayor escala han sido las experiencias de gestión local participativa de los años 80 y 90s en el ámbito latinoamericano y nacional[1], que contaron con el apoyo de los organismos no gubernamentales de desarrollo y de las agencias de cooperación internacional.
En estas circunstancias la Participación Ciudadana encuentra su entorno específico para afianzar y consolidar una gestión de gobierno local concertado y participativo a través de los diversos espacios (mesas de concertación, consejos de coordinación local comités vecinales) y mecanismos (plan estratégico concertado, presupuesto participativo, vigilancia y control ciudadano) que instituye el marco legal vigente[2].
Es así que el Presupuesto Participativo se convierte en un instrumento importantísimo que genera oportunidades para impulsar el desarrollo con equidad, sostenibilidad y alcanzar mejores niveles de vida del poblador, por lo tanto esto permitirá facilitar que se complementen la democracia representativa con la democracia participativa; es decir, permite asignar a los diversos actores sociales un rol insustituible en la gestión de su desarrollo, como ciudadanos con plenos derechos y facultades para decidir, en todo momento, sobre su futuro.
En los últimos años, se han producido importantes experiencias en la promoción del desarrollo local y en la gestión de los gobiernos locales, en base a la Participación Ciudadana en el Presupuesto Participativo sobre todo se logre alcanzar mejoras en la vida de los pobladores de un determinado territorio, sin embargo, esto se debe expresar en el cumplimiento eficiente del presupuesto planificado y de los acuerdos establecidos para mejorar la calidad de vida del poblador y al mismo tiempo, se requiere una cierta madurez de los procesos participativos para avanzar hacia mayores niveles de democratización.
Sin embargo encontramos muchas limitaciones en estos procesos participativos veamos algunos puntos: a ello se suma la pésima importancia de parte de las autoridades locales de conocer y fortalecer los niveles y el grado de participación ciudadana en los procesos del Presupuesto participativo, por lo tanto la participación ciudadana es vista como un obstáculo y no como una fortaleza por algunos alcaldes, en otros casos el proceso del presupuesto participativo solo se realiza por cumplir, también vemos los incumplimientos de los acuerdos establecidos en cada proceso participativo, también estos procesos genera demasiada expectativa y pocos resultados e incluso la atomización del presupuesto y así podemos señalar varios aspectos.
Por lo tanto, lo que se pretende alcanzar en el presente documento son algunos elementos que permitan analizar las limitaciones u oportunidades que tiene los procesos de los presupuestos participativos a nivel del sur peruano[3].
En el sur peruano tenemos las condiciones y la existencia de un marco legal favorable para poner en práctica el derecho de Participar en los procesos del Presupuesto Participativo; por un lado tenemos experiencias exitosas que son motivo para poder replicarlos en otros territorios, y por otro lado también existen organizaciones e instituciones especializadas que están contribuyendo en el fortalecimiento de la democracia[4].
A manera de hipótesis podemos señalar que los problemas encontrados pueden enfrentarse si se logra combinar el liderazgo democrático de los alcaldes; voluntad política para promover la participación y cumplir con los acuerdos; una mayor capacitación de la sociedad civil y la eliminación de las trabas burocráticas que dificultan la participación ciudadana, es decir realizando trabajos articulados y planificados.
Desarrollo
Desde una perspectiva deductiva en el país han transcurrido casi una década desde que se promulgó la Ley 26300, Ley de Participación y Control Ciudadanos que estableció las reglas generales para el ejercicio de los mecanismos de participación y vigilancia ciudadana en el Perú;  desde que se promulgó la Ley de Bases de la Descentralización donde señalaba que las municipalidades deben debatir sus planes y presupuestos con la participación de sus vecinos;  después que se promulgó la nueva Ley Orgánica de Municipalidades donde se estableció el presupuesto participativo en el Perú y  desde que se promulgó la Ley Marco del Presupuesto Participativo. Estas normas fueron una consecuencia de las reformas introducidas por el gobierno democrático del presidente Valentín Paniagua y marcaron un hito frente a las formas cómo los ciudadanos se relacionaban con sus representantes.
Sin duda las experiencias desarrolladas en el Perú específicamente en el sur peruano han sido muy ricas y los procesos participativos han experimentado un proceso de aprendizaje, de oportunidades y de ajuste. Sin embargo, subsisten una serie de problemas que la legislación no ha podido solucionar o en algunos casos ha generado trabas al proceso.
Por lo tanto diversas organizaciones de la sociedad civil (especialistas, ONGs, investigadores, y lideres sociales, etc.) han advertido los problemas y ventajas u oportunidades que existen en torno a los procesos de participación ciudadana a nivel de gobiernos locales en los procesos del presupuesto participativo.
Veamos a continuación algunos conceptos que nos ayudaran a analizar mejor lo que queremos plantear:
Definición de presupuesto participativo utilizado en experiencias concretas[5]
El presupuesto participativo ha sido definido de diferentes maneras: a juzgar por su concepción, según sus enfoques o énfasis y de acuerdo con la experiencia asociada a este. Se ha identificado hasta cuatro formas de definir el presupuesto participativo, por el énfasis particular de algunos de sus componentes:
1. Como técnica o mecanismo de participación:
Es una técnica de presupuestación abierta hacia determinados sectores de la administración pública o de la población destinataria, en la cual se establecen consensos en cuanto a la aplicación y plazos de los recursos disponibles.(Aníbal Barreto, Argentina, 2002)
2. Como un sistema de formulación del presupuesto publico:
El presupuesto participativo es básicamente un sistema de formulación y de seguimiento del presupuesto mediante el cual la población determina, a través de debates y consultas donde serán hechas las inversiones, cuales son las prioridades, obras y acciones a ser desarrolladas por el gobierno, es decir es una valiosa herramienta de planificación presupuestaria (Julio Díaz Palacios, 2001).
3. Como una manera democrática de gestionar las ciudades o los pueblos:
El presupuesto participativo es una forma pública de poder, no estatal, si no civil. Es a través del presupuesto participativo que el ciudadano puede participar en el poder municipal y decidir sobre el conjunto del presupuesto, esto significa mayor democracia, ya que el gobierno pasa a ser ejercido también por la población. Escuchar la voz del ciudadano, individual o colectivamente y de forma permanente; hacer del sector publico un instrumento al servicio de la mayoría de la población y controlar y distribuir la riqueza que generan los impuestos pagados por todos es el desafío que la administración popular se planteo al poner en marcha el presupuesto participativo. (Prefeitura de Porto Alegre, Brasil, 1998).
4. Como un proceso político de empoderamiento de la ciudadanía.
El presupuesto participativo es un procedimiento que permite la participación de los vecinos en la elaboración, definición y control del presupuesto opinado sobre el gasto, la inversión, los recursos y el control de la actividad financiera del sector público (Escuela Mayor, experiencia de Huamachuco, Perú, 2000)
5. Como un Instrumento.
El Presupuesto Participativo es un instrumento de política y a la vez de gestión, a través del cual las autoridades regionales y locales, así como las organizaciones de la población debidamente representadas, definen en conjunto, cómo y a qué se van a orientar los recursos, teniendo en cuenta los Objetivos del Plan de Desarrollo Estratégico o Institucional, según corresponda, los cuáles están directamente vinculados a la visión y objetivos del Plan de Desarrollo Concertado (Ministerio de Economía finanzas, Perú, 2008)
Finalmente podemos decir que el presupuesto participativo es un proceso social y político que busca la distribución equitativa del poder y la construcción de un espacio común entre el estado y la población, fortaleciendo la ciudadanía a través de la deliberación, decisión, gestión y control del presupuesto publico.
Como surge la participación ciudadana en nuestro país:
La Participación Ciudadana surge con la Constitución Política de 1979. En el Título I Derechos y Deberes Fundamentales de la Persona, en su Capitulo I De la Persona, el artículo 2º numeral 16 estipulaba que toda persona tenía el derecho: “A participar, en forma individual o asociada, en la vida política, económica, social y cultural de la nación”. Concordante con dicho precepto, el artículo 64º de la misma Carta Fundamental establecía que: “Los ciudadanos tienen el derecho de participar en los asuntos públicos, directamente o por medio de representantes libremente elegidos en comicios periódicos y de acuerdo con las condiciones determinadas por ley”
Así mismo veamos en la actual Constitución Política de 1993, en su Título I De la Persona y de la Sociedad, Capítulo I Derechos Fundamental de la Persona, en su artículo 2º, numeral 17 prescribe que toda persona tiene derecho: “A participar, en forma individual o asociada, en la vida política, económica, social y cultural de la nación. Los ciudadanos tienen, conforme a ley, los derechos de elección, de remoción o revocación de autoridades, de iniciativa legislativa y de referéndum”.
Veamos como se define Participación Ciudadana[6]: “… las lecciones de las últimas décadas han demostrado claramente que la participación en el desarrollo está íntimamente relacionada con la eficacia del mismo. Las iniciativas de desarrollo tienen mayores probabilidades de alcanzar sus objetivos si las personas afectadas y beneficiadas por las mismas participan en la identificación, diseño, ejecución y evaluación de dichas iniciativas (…) la participación en el desarrollo lleva a una mayor sustentabilidad (…) tiende hacia la descentralización y democratización del poder”.
También debemos destacar que la participación ciudadana en los procesos del presupuesto participativo en nuestro país, tiene una corta historia, se puede decir que surge a fines de la década de los 90, bajo el influjo de la difundida y exitosa experiencia de porto alegre Brasil (1989), ya en 1993 en el distrito de Limatambo, provincia de Anta, en Cusco y en 1999 en Villa el Salvador, distrito metropolitano de Lima y en la provincia Sureña de Ilo se iniciaron procesos de participación ciudadana, que formalmente fueron las primeras experiencias del presupuesto participativo en el Perú.
Sin embargo, esta experiencia es un hito mas en el largo proceso de participación social, estrictamente, no es una experiencia importada de Brasil, si no es el resultado de una trayectoria de movilizaciónsocial de pobladores urbanos y comunidades rurales que buscaron y aun buscan mejorar sus condiciones de vida. (Grey: 2002).
Ahora veamos cuales son los problemas que se encuentran en estos procesos participativos:

a) La participación ciudadana es vista como un obstáculo y no como una fortaleza por algunos alcaldes: A nivel nacional pocos son los alcaldes que realmente tienen una vocación participativa y que promueven estos mecanismos. A menudo existen voces que expresan su incomodidad ante el presupuesto participativo y que consideran que los ciudadanos no están preparados para debatir planes y proyectos. Existen funcionarios públicos que consideran que la participación ciudadana entorpece su trabajo y no asumen todavía que la nueva gerencia pública no se puede concebir al margen de los ciudadanos.[7]

Podemos observar que la participación ciudadana en las regiones del sur peruano también para muchos alcaldes es un obstáculo, desde nuestra experiencia podemos citar un caso fehaciente es que en la mayoría de los distritos no existe CCLs funcionando y mucho menos los comités de vigilancia ciudadana activos, debido a que la mayoría de los alcaldes consideran que estos espacios o mecanismos son una traba para su gestión, es decir ven la participación como una amenaza o confrontación a su gestión y no lo ven como una oportunidad para gestionar el desarrollo local con la participación de la población en general.
b) Baja calidad de la participación: no se ve más allá de su comunidad o del barrio: He tenido la oportunidad de acompañar procesos en la provincia de Antabamba y demás distritos (Apurímac), en el Collao - Ilave (Puno) y en San Jerónimo (Cusco), además tuve la oportunidad de conversar con funcionarios y autoridades municipales existe una coincidencia en torno al nivel de participación de la población, por lo tanto hay la necesidad de mejorar la calidad de la participación ciudadana. A menudo los representantes de las organizaciones sociales ya sean presidentes comunales, lideres sociales, dirigentes y los vecinos no logran consolidar una visión macro más holística ni debatir los grandes problemas de su territorio, aun persisten en atomizar el presupuesto local.
Es cierto que el Perú es un país de grandes carencias y que las necesidades más básicas no son satisfechas, pero también es cierto que los participantes muchas veces sólo se enfocan en solucionar pequeñas demandas de la comunidad o el barrio. Unido a esto, en el caso del presupuesto participativo, las organizaciones vecinales y las comunidades desconocen lo que es un proyecto de inversión o cómo funciona la dinámica de este proceso, afectándose así la calidad de la participación y esto conlleva a la atomización del presupuesto obviamente por que priman los pedidos y no se enfocan a la solución de sus principales problemas que se tienen que solucionar en su territorio.
c) Los representantes no cuentan con suficiente apoyo para ejercer sus derechos de participación ciudadana en la gestión local: Cuando uno conversa con dirigentes comunales, lideres sociales y vecinos de los distritos del sur peruano es común escuchar que a menudo no cuentan con apoyo de sus propias organizaciones al que representan incluso de sus propios vecinos para poder ejercer de manera eficiente su derechos de participar en la gestión local, ejemplo la vigilancia ciudadana, es decir los Comités de Vigilancia, no cuentan con el apoyo que necesitan de sus propias organizaciones e instituciones que realicen un “acompañamiento” en su proceso de fiscalización. Y a esto se suma el desconocimiento de sus funciones y responsabilidades para ejercer eficientemente el control social con instrumentos legales necesarios.

d) Los costos de la participación son económicamente altos: Igualmente conversando con dirigentes comunales, barriales, lideres sociales y representantes de la sociedad civil, también encontramos otro aspecto importante es el costo que ocasiona cuando uno participa activamente en la gestión del desarrollo local, es decir ejercer nuestros derechos como ciudadanos tiene un costo innegable y más aún tratándose de dirigentes vecinales, rurales  o de organizaciones sociales de base que pertenecen a realidades pobres[8]. Existen problemas para que las organizaciones de la sociedad civil participen en los presupuestos participativos provinciales y distritales por los costos que tienen que asumir de transporte, alojamiento, alimentación, materiales, entre otros, durante todo el proceso participativo, Otro ejemplo es para ejercer la vigilancia ciudadana tiene un costo en dinero, por ejemplo si se desea hacer una denuncia se necesita un abogado que los asesore y esto necesariamente es dinero. A esto se suma que los representantes tienen que priorizar sus actividades personales, familiares como ellos manifiestan a veces se pierde tiempo, dinero y al final en todo el proceso no hay resultados concretos.

e) Existe frustración por incumplimiento de los acuerdos del presupuesto participativo y la atomización del presupuesto:  A menudo también escuchamos casos de municipalidades que no han cumplido con ejecutar la totalidad de sus presupuestos participativos programados un año anterior ya sea por problemas de tipo administrativo, porque no tienen capacidad técnica para formular proyectos adecuadamente en función al enfoque SNIP ó porque no han tenido la voluntad política de respetar los acuerdos realizados con sus vecinos y representantes en los diferentes procesos esto obviamente genera frustración por que dichos acuerdos no se cumplen y esto genera desconfianza para futuros procesos participativos.
Si a esto le sumamos que los montos que se asignan al presupuesto participativo son bastante reducidos (el Foncomún), además dichos presupuestos son atomizados en pequeños proyectos que no son de envergadura al estilo de una repartición de una torta y por natural esto va generar un desencanto y frustración en las organizaciones.

f) Se genera demasiada expectativa y no hay resultados concretos: A menudo escuchamos a nivel del sur peruano en los diferentes procesos participativos al cual hemos sido testigo, versiones que los propios actores manifiestan: “Todos los años vamos al presupuesto participativo, identificamos bastantes proyectos y al final no hay resultados concretos”, ocasionando demasiadas expectativas en la población y esto genera frustración como mencionábamos anteriormente, a pesar de que se han desarrollado procesos participativos óptimos metodológicamente hablando, identificando adecuadamente la solución de sus múltiples problemas, priorizando proyectos de gran envergadura en cada uno de los ejes temáticos de un determinado territorio pero al concluir el proceso no se logro concretar dichos proyectos priorizados y el factor principal se puede decir es el poco presupuesto que cuenta dicha municipalidad[9].

g) Los presupuestos participativos se convocan sólo por cumplir con la ley: Este aspecto se relaciona con el ítem “a”, que dice: “a nivel nacional pocos son los alcaldes que realmente tienen una vocación participativa y que promueven estos mecanismos”, para el caso sur peruano que estamos analizando varias municipalidades no realizan un esfuerzo por convocar a la mayor cantidad de vecinos, comunidades y organizaciones de la sociedad civil para el proceso del presupuesto participativo cada año, limitándose únicamente a cumplir con lo que manda la ley y realizando procesos con escasa participación ciudadana, muchas veces improvisando, es decir no son procesos debidamente planificados. Así se desnaturaliza el presupuesto participativo como espacio de diálogo y concertación entre los actores locales y se limita únicamente a talleres con unos pocos participantes, donde los acuerdos no son ni socializados ni publicitados a todo el territorio o localidad.

h) Pésima articulación intergubernamental en la formulación de planes de desarrollo y presupuestos participativos: A nivel nacional existen una serie de normas que marcan la ruta que debe seguirse para el proceso presupuestario que parten de la necesidad de compatibilizar los planes de desarrollo a nivel nacional, sectorial, regional y local; sin embargo, los resultados no son alentadores y es uno de los problemas que enfrenta el sector público cuando formula sus presupuestos, es decir cada instancia de gobierno o sector realiza independientemente sus planes de desarrollo local y los presupuestos participativos y esto muchas veces genera duplicidad en las actividades que se realiza en un determinado territorio, no hay la voluntad política de algunas autoridades en realizar trabajos articulados desde el nivel comunal hasta el nivel regional o nacional[10]. Existen diversas causas como la falta de capacitación en materia de planificación, consideraciones políticas, la ausencia de un liderazgo que aglutine esfuerzos y la improvisación con la que se trabajan las políticas públicas a esto se suma que el Consejo Nacional de la Descentralización fracasó en su rol y su desactivación ha generado un vacío que no ha sido posible llenar. Es necesario que el Ceplan empiece de una vez a trabajar y que la inmediatez deje de estar presente en las políticas públicas. Esta falta de articulación entre planes y presupuestos debilita a los presupuestos participativos y produce duplicidades de esfuerzos y proyectos.
Ahora veamos las oportunidades que han generado los procesos participativos:
a) Cambio en la tradicional manera de tomar decisiones: A nivel nacional en la toma de decisiones dio un giro de noventa grados, ahora la población participa directamente en la toma de decisiones específicamente en la forma de realizar los gastos o la gestión misma en sus diferentes niveles de gobierno y etapas de gestión del desarrollo. Decisiones sobre la base de procesos participativos, es decir involucrándose directamente en la identificación, planificación, ejecución y evaluación de la gestión pública y no sobre la base del mejor parecer de la autoridad de turno.
El presupuesto Participativo en sí mismo no es un proceso de ciudadanía. Es un instrumento que puede alimentar la noción de ciudadanía, pero que requiere ser adecuadamente orientado para lograr ese fin, Sin embargo, estos instrumentos aún imperfectos Sirven para crear una práctica, para ejercitar a la población en sus derechos y responsabilidades como ciudadanos y a participar de las decisiones que influyen en sus vidas.
b) Mayor involucramiento social en los asuntos públicos:
La participación ciudadana es considerada como el elemento sustancial para el fortalecimiento de la gestión pública local, en el marco de un nuevo modelo de gobernabilidad que se viene configurando en los últimos años. En este sentido, entendemos que los Estados locales deben garantizar la participación ciudadana a partir de la implementación de espacios y mecanismos efectivos de participación democrática y con poder de decisión, dando cuenta de las nuevas relaciones que se vienen tejiendo entre el Estado y la sociedad civil.
Las experiencias que se vienen implementando en varios distritos del sur peruano, demuestran que los presupuestos participativos se han convertido en mecanismos estratégicos, que permiten mayor involucramiento de la población en los asuntos públicos, es decir la participación ciudadana es considerada como capital social importante en la gestión misma del desarrollo.
c) Los procesos participativos permiten la inclusión de actores locales excluidos en la toma de decisiones, como las mujeres y las poblaciones indígenas.
En los ámbitos locales se reproduce la misma estructura nacional. La presencia de la voz de las mujeres en los Consejos de Coordinación es limitada. A nivel regional sólo el 22% de los representantes son mujeres. El número de organizaciones inscritas para participar en el reciente proceso de elección de los Consejos de Coordinación Regional ha sido de 1,118 en todo el país[11].
El balance de lo avanzado en la descentralización señala que no se ha logrado aún transformar el paradigma centralista que excluye a los grupos culturales no dominantes y que por el contrario éste se reproduce en los ámbitos regionales y locales.
La participación de los representantes de organizaciones sociales de base expresa con claridad cómo las mujeres y los jóvenes tienen mayor presencia en los espacios de sensibilización y/o capacitación y mucho menor presencia en los espacios deliberativos, donde la participación masculina sigue siendo mayor: 70%. Esto se encuentra asociado a carácter territorial del proceso del presupuesto participativo y su vinculación con convertir todo en proyectos de infraestructura urbana.
Entre los representantes de la sociedad civil predominan los actores territoriales, es decir, con intereses esencialmente de carácter local. En promedio quienes más participan son las organizaciones vecinales (36,8%) y luego encontramos a las organizaciones sociales de base como los comedores y vaso de leche (14,7%) y organizaciones educativas, entre ellas las universidades, colegios profesionales, institutos y colegios (13,8%) (MCLP, 2007).
d) Se presenta como una Escuela de Aprendizaje Compartido y se transparenta la gestión
Donde los participantes educan y son educados. En ella los ciudadanos derriban el “mito” del secreto y ocultamiento de la información y el “misterio” en la toma de decisiones, muchos de los Funcionarios que participan en estos espacios comprenden mejor las necesidades de la población, de manera que durante la formulación de proyectos, toman en cuenta el modo de vivencia y necesidades identificadas de la población.
Durante el Presupuesto Participativo los actores políticos y representantes sociales rotan. No participan siempre los mismos y los mecanismos de votación varían. No es evidente que se pueda dar un proceso de aprendizaje de quienes participan, pero esto puede ser tomado como una oportunidad, ya que estos conceptos son comprendidos por más ciudadanos, que participan en estos espacios de concertación.
Así mismo durante la etapa de Capacitación, se da a conocer las competencias de cada nivel de gobierno y el marco normativo que permite la ejecución de inversiones, así como los costos de funcionamiento, lo cual genera nuevos conocimientos, nuevos aprendizajes en la población y por consiguiente hace que la gestión sea más trasparente en el uso de los recursos económicos.
e) Aparecen nuevos líderes
Durante el presupuesto participativo de muchas localidades, se presentan ciudadanos los cuales tienen aspiraciones Políticas, quienes con su participación, y observaciones, se dan a manifestar como futuros candidatos políticos, los cuales muchas veces, presentan alternativas, lo cual es provechoso, para la localidad.
Así mismo participan en estos espacios representantes de la sociedad civil, quienes aportan sus conocimientos técnicos.
f) Articulación de los planes de desarrollo concertados en los diferentes niveles de gobierno y con los distintos procesos de participación ciudadana para alcanzar el desarrollo de una localidad determinada.
En la práctica los planes concertados de desarrollo vienen siendo, antes que instrumentos de gestión, el nuevo pacto social que se establece en el territorio. Las visiones de desarrollo y las líneas estratégicas terminan concentrando las voluntades sobre el cómo debiera ser el territorio. Suman posiciones y todas deben verse incluidas en ella. Sin embargo, en muchos casos dista de ser un instrumento desagregado a niveles tales que incluyan los programas, proyectos e indicadores de medición que permitan un seguimiento y evaluación de los resultados, no sólo por parte de las instancias de gobierno sino de las demás instituciones existentes en el territorio, públicas o privadas. En la construcción de estos planes de desarrollo se han visto comprometidas las organizaciones sociales de base, pero han estado ausentes los que precisamente pueden ayudar a impulsar el desarrollo local como es el caso del sector empresarial. Adicionalmente, tampoco han estado presentes los representantes de los sectores que implementan acciones en el territorio como educación, salud, agricultura, entre otros. Debe sumarse además, lo difícil que resulta la articulación entre los diferentes niveles de gobierno: regional, provincial y distrital. En la mayoría de los casos existe poca articulación entre los planes distritales y regionales y en otros simplemente no existe.
g) El presupuesto participativo constituye un instrumento para la gestión de los Planes de desarrollo concertados, con el cual se garantiza el cumplimiento de los objetivos trazados.
Sin embargo, son pocos los casos donde la priorización de obras del presupuesto participativo guarda una relación estrecha con el plan concertado. La priorización casi siempre termina siendo un “listado de obras pequeñas” [12] que expresan de un lado, la búsqueda por la justicia en la distribución de los recursos y de otro lado, la débil capacidad local para expresar una visión estratégica de desarrollo.
El tema de discusión a la hora de definir las priorizaciones de los proyectos son las necesidades inmediatas: veredas, parques, locales comunales, etc. La evaluación de la Dirección de Desarrollo Urbano de la Municipalidad de Villa El Salvador en el 2003, se centraba en los costos de mantenimiento que no estaban previstos al momento de ejecutar las obras, costos que después deben ser recargados a los escasos recursos municipales. Además, muchas de las obras que se priorizaron como parques o áreas verdes no incluyeron los costos de mantenimiento posteriores, perdiéndose incluso esa inversión.
Conclusiones:

A manera de conclusiones podemos citar algunos aspectos importantes que consideramos importante en el presente ensayo:
La participación ciudadana debe partir en nuestro medio de considerar nuevas formas de inclusión, consulta y movilización social con la finalidad de informar además de ejercer influencia sobre instituciones y políticas que afectan la vida de la comunidad. Para ello es necesario que la sociedad civil sea activa y comprometida, con capacidad de expresar sus demandas propiciando espacios de concertación y diálogo para la co-gestión del territorio, consolidando así la gestión del gobierno local.
El Presupuesto Participativo se convierte en un instrumento importantísimo que genera oportunidades para impulsar el desarrollo con equidad, sostenibilidad y alcanzar mejores niveles de vida del poblador, permitiendo complementar la democracia representativa con la democracia participativa. Al mismo tiempo debe permitir la renovación de los liderazgos locales y el fortalecimiento de las identidades a partir de la construcción de una visión de conjunto.
En los últimos años en el sur peruano la participación ciudadana en los presupuestos participativos han logrado importantes avances que contribuyeron a alcanzar mejoras en la calidad de vida de los pobladores de un determinado territorio con cierta madurez y que avanzan hacia mayores niveles de democratización, por lo tanto las oportunidades o los aciertos que se ha logrado alcanzar aun queda por fortalecer estos aspectos por ejemplo: la promoción del mayor involucramiento social en los asuntos públicos, esto va permitir la inclusión de los actores locales excluidos en la toma de decisiones, así mismo aparecen nuevos lideres por que en estos espacios participativos son una especie de escuela de aprendizaje compartido y se transparenta la gestión, con un enfoque articulador e integrador entre los diferentes niveles de gobierno en los distintos procesos de participación ciudadana para alcanzar el desarrollo de una localidad determinada haciendo realidad los planes de desarrollo concertados que son la guía para lograr el bienestar de los pueblo.
No existen fórmulas mágicas o modelos estándares para desarrollar procesos de gestión participativa, los fenómenos sociales son complejos con avances y retrocesos. Pero debemos ser conscientes que si bien constituyen de un lado una gran oportunidad para fortalecer a nuestras débiles democracias, por otro lado, pueden convertirse en un arma de doble filo si son usados para cooptar y utilizar la participación ciudadana con otros fines.
A manera de conclusión final podemos señalar que los problemas u oportunidades encontrados pueden enfrentarse si se logra combinar el liderazgo democrático de los alcaldes; voluntad política para promover la mayor participación, cumplir con los acuerdos, una mayor capacitación de la sociedad civil, gestionar transparentemente y la eliminación de las trabas burocráticas que dificultan la participación ciudadana sobre todo ejerciendo el control social.
________________________________________
[1] Formalmente surge a fines de los 80, bajo el influjo de la exitosa experiencia de Porto alegre Brasil (1989 hasta la actualidad) y en 1993 en el distrito de Limatambo, Provincia de Anta, en Cusco y en 1999 en Villa el Salvador, distrito metropolitano de Lima y en la provincia Sureña de Ilo, Son referencias del libro ”Democratizando el presupuesto publico”, Autores: Carlos Grey, Guadalupe Hinojosa y José Ventura – CARE PERU, año 2003.
[2] Ley 26300, Ley de Participación y Control Ciudadanos que estableció las reglas generales para el ejercicio de los mecanismos de participación y vigilancia ciudadana en el Perú.
[3] Enfocándonos en nuestras experiencias profesionales y tomando en cuenta la opinión de algunos dirigentes sociales de estas tres regiones del sur peruano (Apurímac, cusco y Puno).
Análisis de un blog sobre participación ciudadana de Jimena Sánchez Velarde.
http://descentralizacionverdadera.blogspot.com/2009/07/problemas-en-los-procesos-de.html.
Tesis de Economía, UNMSM, “Experiencias significativas del presupuesto participativo que contribuyen a un mejoramiento del manejo de los recursos públicos de Héctor Jaime Castro Pérez,http://sisbib.unmsm.edu.pe/BibVirtualData/monografias/empresa/castro_ph/castro_ph.pdf.
[4] En las tres regiones que estamos analizando existen muchas ONGs, que trabajan este tema.
[5]Existen muchas definiciones pero me parece interesante lo que plantean el libro, ”Democratizando el presupuesto publico”, Autores: Carlos Grey, Guadalupe Hinojosa y José Ventura – CARE PERU, año 2003, pág. 37.
[6] Según referencia del BID, año 2000.
[7] Análisis sobre participación ciudadana caso peruano, autora: Jimena Sánchez Velarde. Año 2009.
http://descentralizacionverdadera.blogspot.com/2009/07/problemas-en-los-procesos-de.html.
[8] Caso sur peruano, Apurímac, Cusco y Puno, son consideradas regiones de extrema pobreza y pobre.
[9] Específicamente la región Apurímac, caso provincia y distritos de Antabamba, año 2007.
[10] Cada Municipalidad  cumple con su proceso del PP, independientemente, igual es el proceso regional. A esto se suma la poca participación de la sociedad civil en estos procesos desarticulados.
[11] Las regiones con menor participación fueron: Pasco (9), Tumbes (17), Ayacucho (19), Ucayali (19), Amazonas (22) e Ica (24).
[12] En el caso del distrito de Lurín, se ha destinado cerca de millón y medio de soles a obras de este tipo; es decir, US$ 7 per cápita, para la construcción de locales comunales multiusos, campos deportivos, enripiado, proyectos de agua y desagüe, cerco perimétrico, etc.


			</p>
		</article>